### ISSUE TITLE
Split between video qualities

### ISSUE THREAD

**Issue by rafa8626** [mediaelement/mediaelement-plugins#1]
_From @isantolin on January 20, 2017 18:38_

@ron666 Like Youtube, can add a feature to split between video qualities, or "Auto" for autosplit by bandwidth analisys?

_Copied from original issue: johndyer/mediaelement#2008_

**Comment by rafa8626** [comment]
@jimmywarting The branch `media-qualities` has now this feature integrated. If you can test it so I can merge it into the master branch, I'd appreciate it. Thanks

**Comment by rafa8626** [comment]
Branch merged into master.

**Comment by KhodyrevDS** [comment]
Does quality plugin support dash renderer?

**Comment by rafa8626** [comment]
Yes it should
