### ISSUE TITLE
Is it possible to play 360 degree videos using mediaelement player

### ISSUE THREAD

**Issue by Danishkthomas** [mediaelement/mediaelement-plugins#102]
Hi ,
I would like to use 360 degree videos on my project. Is it support 360 degree video playing feature?
If yes, how can I implement that feature. Thanks in advance, for your help and valuable suggestions.

**Comment by rafa8626** [comment]
There's a branch `vrview` that integrated Google VRView, but I never got to finalize the testing. On the other hand, https://github.com/yanwsh/videojs-panorama/blob/feature/standalone/index_mediaplayer.html shows how to integrate VideoJS Panorama with MEJS using the `feature/standalone` branch. That's all the support it currently has. Thanks and please star the project to support it

**Comment by rafa8626** [comment]
Check the branch `vrview` and inside `demo` folder, you will find a `vrview.html` that I just tested and worked. Maybe there are still some issues with fullscreen but we can work them out

**Comment by rafa8626** [comment]
I will just add examples of each plugin and then that branch will be merged into master. Thanks

**Comment by Danishkthomas** [comment]
Thank you Rafael.
