### ISSUE TITLE
Hi Im using wordpress Plugin but player is not working with Youtube embed 

### ISSUE THREAD

**Issue by vibhi19** [mediaelement/mediaelement-plugins#103]
Can You help Me with it 

How to use this Plugin to play youtube and dailymotion video

**Comment by rafa8626** [comment]
You may have to ask this in the WP forum and provide more details about your issue

**Comment by vibhi19** [comment]
Ok can You tell me How can I Use http://www.mediaelementjs.com/ this player on a wordpress website using The script i tried but failed Please a Little help will be appreciated

**Comment by rafa8626** [comment]
I'm not an expert on WP, but I know that generally speaking they set up the script at the footer file of your theme; DailyMotion is not covered by default in WP (YouTube does) but you can add it there as well. So something like this may help you:
```html
<script src="/path/to/renderers/dailymotion.js"></script>
<script>
jQuery(function ($) { 
    $('video, audio').mediaelementplayer({
         stretching: 'responsive', 
         classPrefix: 'mejs-'
    });
});
</script>
```
You can use https://github.com/mediaelement/mediaelement/issues/2450 and https://github.com/mediaelement/mediaelement/issues/2449 for reference. 

Please star the project to support it

**Comment by vibhi19** [comment]
I Got css and put your code but i cant find the Js File of mediaelemetjs player can You give its cdn Link

**Comment by vibhi19** [comment]
got it

**Comment by vibhi19** [comment]
Hi Its working http://xvid.ihostfull.com/3708-2/ here but One Problem is that i used Noramal youtube links and embed code and is There anyway i can add support to oembed Youtube and iframe Video dailymotion too

**Comment by rafa8626** [comment]
What do you mean by oEmbed?

**Comment by rafa8626** [comment]
I think if you set iframes it should work as well. Just change your jQuery selector:
```javascript
jQuery(function ($) { 
    $('video, audio, iframe').mediaelementplayer({
         stretching: 'responsive', 
         classPrefix: 'mejs-'
    });
});
```
I haven't tested completely like that but as far as I know it should work

**Comment by rafa8626** [comment]
One thing I noticed in your page you are referring `mediaelement-and-player.min.js` twice; don't do that or you will experience issues

**Comment by vibhi19** [comment]
Yeah Thank You I mean oembed  and i also used iframe as well in some post thank you i test it

**Comment by vibhi19** [comment]
I will check and Remove the  mediaelement-and-player.min.js

**Comment by vibhi19** [comment]
```
Query(function ($) { 
    $('video, audio, iframe').mediaelementplayer({
         stretching: 'responsive', 
         classPrefix: 'mejs-'
    });
}); 


```

Not working brother

**Comment by rafa8626** [comment]
Put it on a Fiddle or a code snippet showing me your HTML so I can check what is the issue

**Comment by rafa8626** [comment]
Or do it on your URL above so I can see if there are any issues

**Comment by rafa8626** [comment]
Interesting. If I use vanilla JS it works for me:
```javascript
var mediaElements = document.querySelectorAll('video, audio, iframe'), i, total = mediaElements.length;

	for (i = 0; i < total; i++) {
		new MediaElementPlayer(mediaElements[i], {
			stretching: 'responsive',
			classPrefix: 'mejs-'
		});
	}

```

**Comment by vibhi19** [comment]
I put the into footer if you wanna try i can provide you username password
noproblem its a test site

**Comment by vibhi19** [comment]
also Used vanila js code still same issue

**Comment by rafa8626** [comment]
It must be something in your code. I used jQuery as well and it works for me:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MediaElement.js 3.0 - audio/video unification library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../build/mediaelementplayer.css">
</head>

<body>

    <div id="container">
        <section>
        <h1>MediaElement.js</h1>
        <div class="players" id="player1-container">

            <h3>Video Player</h3>

            <div class="media-wrapper">
                <iframe id="player1" src="https://www.youtube.com/embed/QILiHiTD3uc" frameborder="0" allowfullscreen=""></iframe>
            </div>
    </div>

<script
    src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
    crossorigin="anonymous"></script>
    <script src="../build/mediaelement-and-player.js"></script>
    <script src="../build/renderers/dailymotion.js"></script>
    <script>
        jQuery(function ($) {
            $('video, audio, iframe').mediaelementplayer({
                stretching: 'responsive'
            });
        });
               
    </script>
</body>
</html>
```
<img width="608" alt="screen shot 2017-11-17 at 2 24 10 pm" src="https://user-images.githubusercontent.com/910829/32964983-068af4b8-cba3-11e7-8d62-e0ec88870151.png">

**Comment by vibhi19** [comment]
Working Brother thank you verymuch made a lillte mistake

**Comment by vibhi19** [comment]
You are The Best

**Comment by rafa8626** [comment]
u r welcome man glad I could help you

**Comment by rafa8626** [comment]
please just star the project to support it

**Comment by vibhi19** [comment]
Yeah sure

**Comment by rafa8626** [comment]
Thanks
