### ISSUE TITLE
Captions/Subtitles on-off toggle button

### ISSUE THREAD

**Issue by smannath** [mediaelement/mediaelement-plugins#104]
Hi, I f I am using single language. Then how can I set captions/subtitles button as toggle on/off instead of hovering disable/enable. Thanks

**Comment by cjcolvar** [comment]
@smannath You can do this by setting the player config `toggleCaptionsButtonWhenOnlyOne` to `true`.  I think the current documentation (https://github.com/mediaelement/mediaelement/blob/master/docs/api.md) has a bug stating the opposite of how it actually works.  I've submitted a PR to clarify the behavior.

**Comment by rafa8626** [comment]
Closing this issue since PR was merged already. Thanks and please star the project to support it
