### ISSUE TITLE
Question about Vast Plugin

### ISSUE THREAD

**Issue by duythien** [mediaelement/mediaelement-plugins#110]
Hello team

I have use plugin https://cdnjs.com/libraries/mediaelement-plugins, and try to config like below

```
var tag = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='

            var player = $('#video-player').mediaelementplayer({
                stretching: 'responsive',
                vastAdTagUrl: tag,
                features: ['playpause', 'progress', 'current', 'duration', 'volume', 'fullscreen', 'vast'],
                // pluginPath: "/path/to/shims/",
                // When using jQuery's `mediaelementplayer`, an `instance` argument
                // is available in the `success` callback
                success: function(mediaElement, originalNode, instance) {
                    // Do something
                }
            });
```
Then I get some error like image below
<img width="713" alt="screenshot at dec 30 13-40-00" src="https://user-images.githubusercontent.com/1762691/34451908-fe7de18c-ed66-11e7-9273-de88b92b0d6e.png">

You can see live version at http://tv.molo.vn/video/we-make-it-awesome/

Anyone have some  problem like that?

**Comment by rafa8626** [comment]
@duythien You need to add https://cdnjs.cloudflare.com/ajax/libs/mediaelement-plugins/2.5.0/ads/ads.js and https://cdnjs.cloudflare.com/ajax/libs/mediaelement-plugins/2.5.0/ads/ads.css before the vast plugin. Please star the project to continue supporting it
