### ISSUE TITLE
playlist youtube as audio

### ISSUE THREAD

**Issue by crashinz** [mediaelement/mediaelement-plugins#112]
new problem,: Why are you only able to hide the playlist in video player?

also just an fyi, i dont care about using old versions but when you use the newest mediaelementplayer.css and mediaelement-and-player.min.js from the master the play and volume buttons disappeared for me

i also tried using this but it wont play youtube audio, is that possible?
https://github.com/jeremejazz/mep-feature-playlist/

I have star'd this project. :)

**Comment by Jad3z** [comment]
@crashinz Great to hear you solved your problem, could you close this issue?

**Comment by berryamin** [comment]
Hello,

    the subject of issue #112 does not match with the contents.
Please open a new issue request for each new issue. Closing for now.
