### ISSUE TITLE
Cannot set property 'mejs.speed-rate' of undefined

### ISSUE THREAD

**Issue by mjacobson7** [mediaelement/mediaelement-plugins#126]
Getting an error after setting up the speed plugin.  When I start my app, this is the error I get:
![2018-03-20_11-31-45](https://user-images.githubusercontent.com/18683764/37671861-47497296-2c32-11e8-8136-274ddf37e5c5.png)

Here is my code:

![2018-03-20_11-32-53](https://user-images.githubusercontent.com/18683764/37671958-797adb92-2c32-11e8-90ac-3a4e9975a2d2.png)
![2018-03-20_11-32-41](https://user-images.githubusercontent.com/18683764/37671961-7cfe4f74-2c32-11e8-88e9-08f82405846e.png)

![2018-03-20_11-33-52](https://user-images.githubusercontent.com/18683764/37672004-9809deb4-2c32-11e8-841c-95becb6bcf41.png)

**Comment by cxanthos** [comment]
@mjacobson7 I'm having the same issue, did you manage to resolve this?
