### ISSUE TITLE
new maintainer for mediaelement-plugins: anyone ?

### ISSUE THREAD

**Issue by berryamin** [mediaelement/mediaelement-plugins#152]
Hello community !

   as you may have noticed, mediaelement-plugins needs a bit of work since some excellent PRs have been stacking here for quite a long time.

   is someone here ready to volunteer a few hours per month to help the project ?

**Comment by Qoraiche** [comment]
@berryamin I'm here 👌

**Comment by berryamin** [comment]
Ha oki great news! Just sent a mail to John Dyer about this

**Comment by Qoraiche** [comment]
@berryamin but I will only maintain the `mediaelement-plugins` not the whole mediaelement.js, can you give John Dyer email

**Comment by berryamin** [comment]
Yes sure. Johndyer at gmail.com
