### ISSUE TITLE
Google Tag Manager missing from dist folder

### ISSUE THREAD

**Issue by KZeni** [mediaelement/mediaelement-plugins#166]
I see it has docs & src, but it's not in dist.

Is there any reason this isn't currently as part of the dist folder? Seems odd it's just in source while all others are then also in dist (which I'm guessing is what https://cdnjs.com/libraries/mediaelement-plugins & others are looking at so GTM is currently not readily available via a CDN due to what appears to be an oversight[?])

**Comment by jaapmarcus** [comment]
I don't know except it didn't exists in the Grunt file that build it...

With the pull request it should be solved.
