### ISSUE TITLE
m4v video not playing in latest version of google chrome

### ISSUE THREAD

**Issue by ramkrishnsaini** [mediaelement/mediaelement-plugins#18]
I am using medialement plugin in my app and it was working fine earlier but suddenly it stopped working in google chrome latest version.

I checked the google chrome version in which it is still working is 53.xxx

and now google chrome updated to 56.xxx.

I tried few thing and one thing that partial worked is when I set type="video/x-m4v". but this is not fully workable in large app.

**Comment by ron666** [comment]
Can you share a URL so I can check this, please?

**Comment by ron666** [comment]
Closing issue since no updates on more than a week.
