### ISSUE TITLE
Installation instructions for node

### ISSUE THREAD

**Issue by CalebKester** [mediaelement/mediaelement-plugins#19]
I'm pretty new to node and trying to get the video working in my vuejs project. It would be great of mediaelement-plugs was an npm package so we could both use npm as well as use import statements to pull it into our code.

Any thoughts?

**Comment by ron666** [comment]
Good point. I'll publish the package later so it's available for everybody. Thanks

**Comment by ron666** [comment]
Done. https://www.npmjs.com/package/mediaelement-plugins
