### ISSUE TITLE
Customize subtitle font/color/size/style from the CC menu

### ISSUE THREAD

**Issue by rafa8626** [mediaelement/mediaelement-plugins#2]
_From @alindt on November 7, 2016 7:36_

It would be a really great feature to be able to customize subtitle font/color/size/style from the CC menu in the player. Maybe even saving those custom settings in some cookies, per site?

Youtube example:
![1](https://cloud.githubusercontent.com/assets/1379385/20049659/25231f3e-a4cd-11e6-87c7-e655b8752373.png)

jwplayer example:
![](https://www.jwplayer.com/wp-content/uploads/blog/implementing-fcc-closed-captioning-mandates/Screen-Shot-2015-01-21-at-2.15.11-PM.png)

_Copied from original issue: johndyer/mediaelement#1919_

**Comment by jimmywarting** [comment]
better to use localstorage then cookies

**Comment by tennety** [comment]
Looking to take a crack at this...was this issue moved here with the idea that while the basic CC feature is part of mediaelement, the menu for the customization would be a plugin?

**Comment by rafa8626** [comment]
Originally I thought that could be another plugin. The more I think about it, the more I see this as a part of the player so other plugins fit in a YouTube settings container (including enhancements to the captions)

**Comment by Dacogetul** [comment]
where can i find this? Cannot move subtitle position up and are hidden in fullscreeen or on the controls player position  on other size screen?
