### ISSUE TITLE
Need demo implement plugin

### ISSUE THREAD

**Issue by lebanggit** [mediaelement/mediaelement-plugins#21]
I have try with sort document at here:
https://github.com/mediaelement/mediaelement-plugins

But failed. Please provide some demo about implement plugin on mediaelement

For Example speed plugin.

**Comment by ron666** [comment]
Thanks for pointing this. I'll create a master demo with some of the visual plugins and let you know when ready

**Comment by ron666** [comment]
@lebanggit You can find now a demo folder that has an index file to show you how to use plugins. Thanks for reporting this
