### ISSUE TITLE
Help in Ads plugin to run on specific event

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [mediaelement/mediaelement-plugins#214]
Hello, at first i wanna say that i'm not so good in javascript.
the thing i'm asking for is, i wanna run a specific function on event such as run function when the ad started playing and run a function when the ad is being clicked on.
Hope someone can show me an example of it.
Thanks in advance

**Comment by jaapmarcus** [comment]
You can use the  mejsprerollstarted and mejsprerolladsclicked  to see when a ad has been played or been clicked

And then execute the function you want

**Comment by Ahmed-Elrayes** [comment]
so i would use them the same way we use success function, right?

**Comment by jaapmarcus** [comment]
Yes

**Comment by Ahmed-Elrayes** [comment]
i see, thanks a lot, i will try it later and give you my feedback

**Comment by Ahmed-Elrayes** [comment]
seems like it's not working, i tried to run the function and make a console.log to check it, but nothing appears..
check the image below
![Image 1](https://user-images.githubusercontent.com/30704271/147955212-3aab79f7-f865-4aea-94b4-f9dfdf18ff7a.png)

**Comment by Ahmed-Elrayes** [comment]
Is there anything you can help me with?

**Comment by Ahmed-Elrayes** [comment]
hey again, hope you can help me when you're here

**Comment by Ahmed-Elrayes** [comment]
@jaapmarcus hey, can you help me in this? :)

**Comment by Ahmed-Elrayes** [comment]
any body here can help?

**Comment by Ahmed-Elrayes** [comment]
since the support in here is kinda bad unfortunately i had to buy ultimate video player on code canyon, Thanks i will close this issue now.
