### ISSUE TITLE
no support for VAST 3.0

### ISSUE THREAD

**Issue by skoften** [mediaelement/mediaelement-plugins#22]
2.0 is supported only :-(

**Comment by ron666** [comment]
Have you tried the latest version of this plugin? I'm not familiarized with what is needed for VAST 3.0 but if you can point it out and provide me a sample URL for VAST 3.0 I can work on it

**Comment by skoften** [comment]
Yes, latest version only supports 2.0 VAST structure. The elements are different, so at this moment when you try to load a VAST 3.0 feed, it generates errors and the player won't play the preroll or video.

Example 2.0: http://www.adotube.com/php/services/player/OMLService.php?avpid=oRYYzvQ&platform_version=vast20&ad_type=linear

Example 3.0, see attachement.

[vast3.0.txt](https://github.com/mediaelement/mediaelement-plugins/files/888500/vast3.0.txt)

**Comment by ron666** [comment]
OK I'll check this and keep you posted when this is ready. Thanks

**Comment by ron666** [comment]
In your example for 3.0 VAST I don't see any `MediaFile` tags. Is that expected? Also, I didn't see a tag with the ID and I'm not sure if the `AdSystem` tag is the title. Can you clarify please?

**Comment by skoften** [comment]
Unfortunately I'm not a specialist on this subject, we only use is as a publisher. Only thing I can say is that 3.0 is a wide used format nowadays.

More info on 3.0 can be found here: https://www.iab.com/guidelines/digital-video-ad-serving-template-vast-3-0/

A nice matrix with version differences: http://adtagmacros.com/2016/10/difference-between-vast-2-0-and-vast-3-0-vast-4-0.html

**Comment by ron666** [comment]
Thanks I'll check this documentation and update the plugin. I'll keep you posted. If you can get me a more robust sample URL I can use for testing purposes I'd appreciate it

**Comment by ron666** [comment]
@skoften I refactor the `VAST-VPAID` plugin and it's now supporting VAST3.0. I tested it with https://raw.githubusercontent.com/chrisdinn/vast/master/test/examples/vast3_inline.xml. Please download the master branch and test it on your side. Keep me posted

**Comment by skoften** [comment]
Hi rafa,

Looks like the player still doesn't parse/read VAST 3.0 feeds. 

Feed: https://ad.360yield.com/advast?p=723265&w=4&h=3
Screenshot;
![screen shot 2017-05-12 at 17 18 40](https://cloud.githubusercontent.com/assets/1286410/26004785/4a1e30c4-3737-11e7-8622-a7871740f417.jpg)

VAST 2.0 works fine.

**Comment by rafa8626** [comment]
Thanks I'll check this in a minute

**Comment by skoften** [comment]
I also have another feed (2.0) that doesn't seem to work:

https://secure.adnxs.com/ptv?id=10256154

**Comment by rafa8626** [comment]
I know the first one will need some work; but the second one IDK what's the issue. It's returning me only `<VAST version="2.0"></VAST>` with nothing inside it.

**Comment by rafa8626** [comment]
I'm currently working on expanding the plugin to support AdsVastURI and JS files as MediaFiles. I'll keep you posted when it's done

**Comment by nadirlc** [comment]
Does the VAST/VPAID plugin support YouTube videos?.

We want to show videos ads using VAST before playing YouTube clips

**Comment by rafa8626** [comment]
It should but just keep in mind that the plugin is very limited in regards of what can parse and present as Ad
