### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by rafa8626** [mediaelement/mediaelement-plugins#23]
_From @isantolin on February 8, 2017 18:51_

@ron666  A lot of players now includes Chromecast support
- VideoJS: https://github.com/benjipott/video.js-chromecast
- Flowplayer: https://flowplayer.electroteque.org/chromecast

Its a good feature, because in the case of Flowplayer is a pay plugin

_Copied from original issue: mediaelement/mediaelement#2065_

**Comment by ron666** [comment]
@isantolin Thanks. I'll check this

**Comment by ron666** [comment]
Since I don't have a Chromecast device, what's the expected output for this?

**Comment by ron666** [comment]
_From @isantolin on February 16, 2017 11:41_

When a Chromecast is configured on Browser, a Player with Chromecast support adds a Button to broadcast content to device.
![sample](https://cloud.githubusercontent.com/assets/264640/23019977/fa99253e-f42b-11e6-9942-012f2b2835e7.jpg)


If you dont have a Chromecast, you can use Cheapcast app to emulate

**Comment by ron666** [comment]
_From @jimmywarting on February 21, 2017 21:39_

+1 (only feature missing for me to swish to elmementjs)

While we are at it. How about adding AirPlay also?
here is a demo: https://jsfiddle.net/8gd83urs/?utm_source=website&utm_medium=embed&utm_campaign=8gd83urs

**Comment by ron666** [comment]
_From @eposjk on February 24, 2017 16:53_

By the way: There is a Web Presentation API ( https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API ) which is already supported by Chrome (seems to be for Chromecast) with an experimental Polyfill which should work without Chromecast ( https://mediascape.github.io/presentation-api-polyfill/ ). What about using that?

**Comment by ron666** [comment]
_From @leocaseiro on February 26, 2017 8:51_

How about this example, is with mediaelement.js, isn't?
http://amoravhad.com/projects/vCast-jQuery/index.html

**Comment by ron666** [comment]
_From @jimmywarting on February 26, 2017 10:35_

Would like something more internal support rather then having some plugin. Casting is something that everyone would want

**Comment by ron666** [comment]
_From @leocaseiro on February 26, 2017 12:1_

Hi @jimmywarting

Thanks for your reply.

 I'm sorry, it was only a reference that uses `mediaelement.js`.

The demo app [CastVideos-chrome](https://github.com/googlecast/CastVideos-chrome) should help with the code as well.

**Comment by ron666** [comment]
_From @leocaseiro on February 26, 2017 12:3_

The [vcast](http://amoravhad.com/projects/vCast/demo/wp-content/plugins/vcast/js/vcast.js) uses a lot from [CastVideos.js](https://github.com/googlecast/CastVideos-chrome/blob/master/CastVideos.js)

**Comment by ron666** [comment]
Thanks all for your comments. I'll check the documentation about this and start working on it. I'll try to include AirPlay. This ticket should be logged in `mediaelement-plugins` repo BTW

**Comment by ron666** [comment]
_From @jimmywarting on February 26, 2017 14:55_

videojs also have plugin for casting

https://github.com/benjipott/video.js-chromecast
https://github.com/jgubman/videojs-airplay

**Comment by ron666** [comment]
_From @jimmywarting on March 14, 2017 17:53_

The advantage with presentation api vs chromecast is that you can also cast to some TV's with DIAL (discovery and launch)

**Comment by andyh4** [comment]
Any movement on this?

**Comment by rafa8626** [comment]
I'm still working on this. I've had some issues on the main player that took precedence. But I'll keep you posted in the course of next week

**Comment by rafa8626** [comment]
@thisanimus, @jimmywarting and @isantolin, I have the `chromecast-support` branch. I don't have a way to test it since I don't own an Android or Chromecast. If you can point me how can I test this using Mac and iOS I'd appreciate it. Otherwise, if you can test and post your issues here also is welcome.

**Comment by thisanimus** [comment]
I'll start testing this afternoon.  If you want to test on your own, a chromecast can be had for ~$30, the only other thing you need is a chrome browser on any platform.

**Comment by rafa8626** [comment]
Thanks. Send me screenshots and expected behaviors if you find any issues, please to speed the completion of this plugin

**Comment by thisanimus** [comment]
Wilco

**Comment by jimmywarting** [comment]
I was able to select chromecast device

![skarmavbild 2017-04-17 kl 18 04 33](https://cloud.githubusercontent.com/assets/1148376/25094629/5eb6e538-2398-11e7-9250-ea9735d509cd.png)

A cast icon turns up on my TV, But i can't see the movie...

I'm seeing this error
```
 [  8.666s] [cast.framework.EventTarget] Handler for isConnectedChanged event failed: TypeError: Cannot read property 'media' of undefined
```

![skarmavbild 2017-04-17 kl 18 06 30](https://cloud.githubusercontent.com/assets/1148376/25094692/a07d2298-2398-11e7-8b76-7a55c64187e7.png)

**Comment by rafa8626** [comment]
@jimmywarting Thanks I'll check this issue. I'm not sure where is this happening on my code. If you can help me pointing where I'd appreciate it. In the screenshot I can't see any references to my code

**Comment by jimmywarting** [comment]
I know, it's weird no reference to your code.

**Comment by rafa8626** [comment]
@jimmywarting Can you do me a favor and download the project of https://github.com/googlecast/CastVideos-chrome, and install it in your localhost and test it please? This seems to be an issue with the library itself and needs to be reported. If not I'll need the whole trace for this error

**Comment by rafa8626** [comment]
Also, download the branch again; I removed some code and allowed a console.error call if any errors with media

**Comment by jimmywarting** [comment]
This is where it fails:
```js
	loadPlayer () {
		const t = this;

		if (!t.media.paused) {
			t.media.pause();
		}
```

this/t is undefined

**Comment by rafa8626** [comment]
Thanks for the hint. I'll check this

**Comment by jimmywarting** [comment]
a simple `.bind(this);` works but that leaves me with the next error...

```js
// Add event listeners for player changes which may occur outside sender appt.castPlayerController.addEventListener(cast.framework.castPlayerEventType.IS_PAUSED_CHANGED, function () {
			if (t.castPlayer.isPaused) {
				t.media.pause();
			} else {
				t.media.play();
			}
		});
```

`castPlayerEventType` is undefined...

**Comment by rafa8626** [comment]
Comment please the lines related to adding events to `t.castPlayerController` and see if you have any issues. I tried to set something with those but it may be overkill and clearly it has issues. Let me know

**Comment by rafa8626** [comment]
And yes I added the bind but I didn't push it. Thanks anyway for the hint

**Comment by rafa8626** [comment]
Nevermind. The code had a typo for those events and I fixed those. Please check the branch again and test

**Comment by rafa8626** [comment]
@jimmywarting @thisanimus Any updates on this after the fixes I posted yesterday?

**Comment by jimmywarting** [comment]
I can't test it at work, don't have a chromecast here so... got to wait a few hours till i get home

**Comment by rafa8626** [comment]
No problem. Thanks for testing this. If there's anything else missing as well let me know

**Comment by jimmywarting** [comment]
Now i don't get any errors 👍 
it kind of works (poorly)

### test 1
 1. When i press the chromecast button then the video is not transmitted. Only a chromecast logo appears on the TV like if it's ready to receive (made a connection)
 2. I refreshed the page and it manage to remember the connection it had with the TV 👍 
now when i press the play button it starts to play the video on both the TV and the website<br><br>Think the poster image should be visible only on the website while playing on the TV

### test 2
 - I disconnected the casting to my TV and did it all over again but this time i have added the volume controller to the demo.
 - I connected to the chromecast (still no video) but i changed the volume on the video without reloading and it reflected onto the TV

----

Btw it says SAMPLE with big red text on the TV 🤣

**Comment by rafa8626** [comment]
Good. I think the SAMPLE comes like that because the cast ID is the one Google uses by default. Unless you obtain a new ID it won't say that anymore. Did you set up the `poster` attribute on your demo file? What else did you experienced, since I can't really test this myself

**Comment by jimmywarting** [comment]
I did some own development before i discovered there was a chromecast plugin to VideoJS. <br>
Then I used the "Default" player and it didn't say "sample"...

**Comment by rafa8626** [comment]
Also if you have screenshots of the console output that would be good to see. In that case, you should use the uncompressed version of `chromecast` plugin instead of the compressed one. Let me know if you have any questions/comments

**Comment by jimmywarting** [comment]
i didn't had any poster...

**Comment by rafa8626** [comment]
Right now it has changed some. They have reduced the code that is needed on our end to implement Cast. the one VideoJS implement is using the version 2.0 and we are using 3.0

**Comment by jimmywarting** [comment]
Okey 👍

**Comment by rafa8626** [comment]
Keep me posted if you can find anything that I'm not aware of or needs to be implemented so I can release the plugin soon. I need to make sure is stable enough to release it, and since you mentioned poorly, I'm not that sure

**Comment by jimmywarting** [comment]
Can start of with making the video start playing directly after you have connected to the chromecast. (without having to refresh the page)

**Comment by rafa8626** [comment]
OK I'll check this later today. Anything else?

**Comment by jimmywarting** [comment]
- Don't play the video on the website... show a poster or 1 frame instead (maybe some onscreen text like "currently playing on: **Living room**")
- If you refresh the page it should get all the metadata from the chromecast session like "currently playing big buck bunny, volume, how far into the movie you are"
- make the play/pause reflect onto the tv so you can pause/resume the video from the website

The seekable maybe work as it should (i manage to seek on website and it skipped on the TV as well)
But something feels out of sync (don't know what, maybe it's cuz the video is playing on the website and continues as if it's playing locally - it should reflect the progressbar it has from the chromecast)

**Comment by jimmywarting** [comment]
example from youtube

![skarmavbild 2017-04-18 kl 19 53 47](https://cloud.githubusercontent.com/assets/1148376/25145222/d964f1c0-2470-11e7-9a50-5b6aace8bbda.png)

**Comment by rafa8626** [comment]
Thanks for the information. I'll give you an update of this soon

**Comment by jimmywarting** [comment]
Setting up events for the `castPlayerController` and updating the media player is easy made 2 PR already, However there is many events that are still missing.

![skarmavbild 2017-04-18 kl 21 27 51](https://cloud.githubusercontent.com/assets/1148376/25149338/5b912aee-247e-11e7-9a30-27597db0166c.png)

The only thing i haven't wrapped around my head is to get the player to show the video initially when you first connect to the chromecast

**Comment by rafa8626** [comment]
I think I know why. I just bought a Chromecast and I'll test tonight. I'll check your PR as well. Thanks

**Comment by jimmywarting** [comment]
Best investment you have ever made 👍 
you won't regret it :)

**Comment by rafa8626** [comment]
:) I'll keep you posted about the final fixes I'll put for this. Thanks for your help

**Comment by rafa8626** [comment]
@jimmywarting I may need to step back and integrate this inside of the `MediaElement` player itself, because of the dual nature of Chromecast. I'll keep you posted on this.

**Comment by rafa8626** [comment]
@jimmywarting I almost have the new work setup for Chromecast. I have a new branch to support AirPlay. Is there a chance you can test it, please? If so, check the `airplay-support` branch.

**Comment by jimmywarting** [comment]
I have a AirPlay here at work that i might be able to test today, but if not then i can install a AirPlay reciver on my android to test it

**Comment by rafa8626** [comment]
Ok thanks keep me posted

**Comment by jimmywarting** [comment]
I installed [airpin (lite)](https://play.google.com/store/apps/details?id=com.waxrain.airplayer&hl=en) on my android to test the airplay

there was but one small issue with the spelling but otherwise it did look good 👍 
Made a PR to fix it

Also `Player` wasn't wasn't available, didn't know where you got that from¿

**Comment by rafa8626** [comment]
My apologies I had a typo. I'll review your PR and merge it. Thanks for testing this and helping me with this

**Comment by jimmywarting** [comment]
No worries, I'm glad I can help

**Comment by jimmywarting** [comment]
How is the Chromecast coming along? Any progress?

**Comment by rafa8626** [comment]
There has been new attempts but I really need to redesign something on the main player to achieve the proper result. It's more complicated than I thought but I'm on that. I'll let you know when I have the new branch on the other repo ready

**Comment by rafa8626** [comment]
@jimmywarting Just FYI, I almost have Chromecast ready. I need to test it tonight, but the tests I ran today showed that it was working as expected. I'm adding a layer to display poster and the name of the device is being casted. If you wanna go ahead and test it right now I'll push it. I don't have a Chromecast here to validate all the changes I made, but if you can help me with that I'd appreciate it. Let me know so I can push the changes on the `chromecast-support` branch

**Comment by jimmywarting** [comment]
I can test it when i get home approximately in 2 to 3 hours

**Comment by rafa8626** [comment]
OK sounds good. Keep me posted please. And again, I don't have a Cast device here to check the last changes I made so potentially I could have made a mistake. Just download the latest version of the branch for this please

**Comment by rafa8626** [comment]
Nm. I need to rework one last piece before you test it @jimmywarting I'll send you tomorrow an status of this. Thanks and sorry for the incovenience

**Comment by rafa8626** [comment]
@jimmywarting You can test it now. I have solved all but 2 things here: 
- If you don't push the button for Chromecast, and try to play the video on the website, it doesn't play
- Need to test more when switching media sources

If you have any clues or ideas on how to solve these 2 items, let me know. I need to step back some since I'm being so involved that I need a second opinion

**Comment by jimmywarting** [comment]
A lot has changed in the plugin from last time. 
A complete new renderer. 
That's new to me.

I tested it the demo and were presented with a video without a poster,
trying to play the bunny video didn't work. nothing happens

**Comment by rafa8626** [comment]
Yeah that's what I still need to figure out how to fix it since it's like basically having 2 players in one, but I tested it connecting to Chromecast and it worked for me

**Comment by jimmywarting** [comment]
Yea, it worked for me too. when i connected to it
Would it be possible to have the chromecast always visible?

removing:
```
button.style.display = 'none';
```

**Comment by rafa8626** [comment]
OK I can remove it

**Comment by rafa8626** [comment]
The only issue is that if the plugin doesn't detect a Chromecast device, it won't show up the button

**Comment by rafa8626** [comment]
I fixed some typos. And if you connect and then disconnect, it will work as expected. I just need to figure out what to do when you haven't connected at all properly

**Comment by rafa8626** [comment]
@jimmywarting I fixed the first issue completely. It should now work as expected. My last task would be to check when loading new sources and see if the method does it correctly. Please test the latest changes on the branch and let me know. If you wanna add any PRs you are welcome to do it. Thanks

**Comment by rafa8626** [comment]
@jimmywarting Once you finish testing Chromecast branch, can you just take a quick look to the AirPlay branch, please? I completed the changes for the button status color and with that I can merge it into the master branch. Let me know how the Chromecast plugin worked for you. I'll be checking the addition of `Tracks API` in Chromecast as well to close the loop on this.

**Comment by jimmywarting** [comment]
Took a quick glance, Looks good

**Comment by rafa8626** [comment]
Great. I just need to finalize the tracks implementation (which is almost done) and more documentation and it will be merged in master. Thanks for testing this

**Comment by jimmywarting** [comment]
question: why do you use thumb instead of poster?
```js
if (mediaElement.originalNode.getAttribute('data-thumb')) {
  mediaInfo.metadata.images = [
    {'url': mejs.Utils.absolutizeUrl(mediaElement.originalNode.getAttribute('data-thumb'))}
  ];
}
```

**Comment by rafa8626** [comment]
I just saw an example and you could have the poster image for the static player and a thumbnail for the cast. I don't know if that's standard or not. I can always remove the thumbnail and only use the poster of needed. Let me know

**Comment by jimmywarting** [comment]
This is only my theory, but I think many will use the same poster as the thumbnail.
I know I would

**Comment by rafa8626** [comment]
OK, changing that, I think the plugin is ready. On a second iteration I'll integrate tracks but I need to know more details about this. So please test the latest version of the branch one more and let me know so I can merge this in the master branch. Thanks

**Comment by rafa8626** [comment]
@jimmywarting Are you good with merging the branch into master? I tried to enable captions before doing this but seems that there's an error setting them and I reported this to Google. So for now it will work without captions. Does that sound good?

**Comment by jimmywarting** [comment]
Sounds good to me

**Comment by rafa8626** [comment]
Excellent. Thanks a lot for your help. I'll keep you posted when captions are working. Closing this ticket since it
