### ISSUE TITLE
Jump forward keeps repeating while skip back doesn't

### ISSUE THREAD

**Issue by openbayou** [mediaelement/mediaelement-plugins#24]
I've noticed that if you keep pressing jump forward button, it repeats to the beginning of the file in a loop. Skip back does not.

**Comment by rafa8626** [comment]
Thanks for reporting this. I'll take a look at it and keep you posted

**Comment by rafa8626** [comment]
@openbayou Check the demo file on the master branch; I added a missing parameter so it doesn't rewind. That's why when you keep pressing the button it repeated.
