### ISSUE TITLE
Can only user Skip back and Jump forward when audio is playing

### ISSUE THREAD

**Issue by openbayou** [mediaelement/mediaelement-plugins#25]
Is there a way to use the skip back and jump forward plugins when the audio player is not playing when the player has loaded for the first time? Currently, the only the way for those plugins to work is when the audio player is playing. When the player has started to play the media file and then pause, you can use those plugins.

Example of what I'm talking about:
[initial/first time loading]
Skip and Jump forward do not work

[player is player]
skip and Jump forward do work

[player is paused]
skip and Jump forward do work

Thanks

**Comment by rafa8626** [comment]
I'll take a look at this and keep you posted. Thanks

**Comment by rafa8626** [comment]
@openbayou I fixed an issue found causing always to point zero when jumping forward in the initial load; please download the master branch and confirm

**Comment by openbayou** [comment]
Download it, does not work.

**Comment by rafa8626** [comment]
That's expected. The plugin does not play the media if you jump back and forth; at least it wasn't designed that way. For the skip back, on the initial load it likely will be zero always unless you have a different scenario; if so can you share a URL where I can see your issues, please?

**Comment by openbayou** [comment]
hmm, interesting. Works fine on player hosted online. Kind of messed up on internal server. http://wpfreelance.bayoumedia.net/audio/

**Comment by rafa8626** [comment]
Closing this issue since behavior has been fixed. If you have any more questions, please let me know
