### ISSUE TITLE
Add support for audioTracks

### ISSUE THREAD

**Issue by rafa8626** [mediaelement/mediaelement-plugins#3]
_From @jrglasgow on October 20, 2016 14:56_

For accessibility reasons we need the ability to have Audio Descriptive tracks which allow blind users to know what is happening in the video.

The audio track HTML element which is not yet supported buy all browsers would cone a long way toward helping with this issue.

http://www.w3schools.com/tags/av_prop_audiotracks.asp

_Copied from original issue: johndyer/mediaelement#1891_

**Comment by ron666** [comment]
_From @jrglasgow on November 7, 2016 18:4_

[I am currently working on a plugin to add this functionality here](https://github.com/jrglasgow/mediaelement_audio_description)

**Comment by ron666** [comment]
@jrglasgow Great. You can create a PR based on `3.x-dev` branch so we can review it

**Comment by ron666** [comment]
@jrglasgow I have started a branch migrating your code to be used with 3.x version. I'll keep you posted about this. Thanks

**Comment by rafa8626** [comment]
Closing this since no answer has been posted in months. If you want this to be reopened, please let us know. Thanks
