### ISSUE TITLE
Set default audio?

### ISSUE THREAD

**Issue by openbayou** [mediaelement/mediaelement-plugins#31]
Is it possible to set the default audio in the player?

**Comment by rafa8626** [comment]
Can you provide an example of what you are trying to achieve please?

**Comment by openbayou** [comment]
Is there a way to set the audio on the player at 5 or 50% when the player starts in the player settings?

	new MediaElementPlayer('audio-player', {
    autoRewind: false,
		features: ['skipback','playpause','jumpforward','current','progress','duration','speed','volume']
    });

**Comment by rafa8626** [comment]
You can set it up specifying the number of seconds from which it will start playing using `#t` with the number of seconds media should start with:
```html
<video width="640" height="360" controls preload="none">
    <source src="http://vodflash.tv5monde.com/focus/legendes/4fils.mp4#t=240" type="video/mp4">
</video>
```
or you can use the `success` callback, and `setCurrentTime` method inside of it.
```javascript
new MediaElementPlayer('audio-player', {
     autoRewind: false,
     features: ['skipback','playpause','jumpforward','current','progress','duration','speed','volume'],
     success: function(media) {
           media.setCurrentTime(3);  // Time in seconds
     }
});
```

**Comment by openbayou** [comment]
startVolume: 0.5,

found it

**Comment by rafa8626** [comment]
I got confused somehow with the position of the player, rather than the audio. My apologies. I'm glad you found it
