### ISSUE TITLE
source-chooser doesn't work on Safari 10.0.3

### ISSUE THREAD

**Issue by ahushh** [mediaelement/mediaelement-plugins#35]
Safari replaces all elements inside `<video>` with 'Shadow Content (User Agent)'.
```
buildsourcechooser: function buildsourcechooser(player, controls, layers, media) {
	var t = this,
		sourceTitle = mejs.Utils.isString(t.options.sourcechooserText) ? t.options.sourcechooserText : mejs.i18n.t('mejs.source-chooser'),
		sources = [],
		children = t.node.childNodes;
```
Children is empty here therefore sources too.

**Comment by rafa8626** [comment]
Thanks for reporting this. I'll proceed to fix this on the plugin. This workflow was added due to an accessibility issue in Safari. I'll keep you posted when fixed.

**Comment by rafa8626** [comment]
@ahushh Can you download the master branch and test again please?

**Comment by ahushh** [comment]
It works, but title attribute is ignored. Can it be fixed?

**Comment by rafa8626** [comment]
Download the master branch of `MediaElement`, it already has that fix.

**Comment by rafa8626** [comment]
Let me know if it worked for you

**Comment by ahushh** [comment]
I'm using master branch and source title is missing.
```
		for (var _i = 0, _total = sources.length; _i < _total; _i++) {
			var src = sources[_i];
			if (src.type !== undefined && typeof media.canPlayType === 'function') {
				player.addSourceButton(src.src, src.title, src.type, media.src === src.src);
			}
		}
```
`src.title` is undefined.

**Comment by rafa8626** [comment]
The master branch of the player itself (https://github.com/mediaelement/mediaelement), not this one, has the fix for the `title` attribute

**Comment by ahushh** [comment]
Yes, it works, thanks!

**Comment by rafa8626** [comment]
Glad to know it worked. Please star us to continue giving the package more popularity, and also tell your friends/coworkers/etc. to support the project, if you don't mind. Also, if you can star us at https://github.com/mediaelement/mediaelement, it would be greatly appreciated it
