### ISSUE TITLE
Set marker width

### ISSUE THREAD

**Issue by leocaseiro** [mediaelement/mediaelement-plugins#38]
I was wondering if we could enable some more styling for markers such as width or any other suggestions.

I'm happy to send a PR for this.

**Comment by rafa8626** [comment]
You are welcome to send PR for this :)

**Comment by rafa8626** [comment]
Any updates on this?

**Comment by leocaseiro** [comment]
Sorry for my delay, I've just sent you a PR.

**Comment by rafa8626** [comment]
No worries. PRs accepted. Thanks for your work
