### ISSUE TITLE
blocking Global Options drop down menu 

### ISSUE THREAD

**Issue by mzen1** [mediaelement/mediaelement-plugins#39]
how to get rid of Global Options drop down menu without deleting audioplayer styles? for multiple players on page.

**Comment by rafa8626** [comment]
Can you expand on this? What drop down menu are you talking about?

**Comment by mzen1** [comment]
this: http://zenonedesign.com/HTML5/demo/index.html
i want multiple players on a page, but when I try to delete the Global Options dropdown section i lose all styling and conditional stopping/playing. the var "lang" is tied into all the styling?i just want the audioplays with no drop down, like almost here: http://zenonedesign.com/HTML5/demo/indexMZ2.html

**Comment by rafa8626** [comment]
Yes you just need this piece of code, rather that the entire content of demos.js file:
```javascript
document.addEventListener('DOMContentLoaded', function () {
	var mediaElements = document.querySelectorAll('video, audio'), i, total = mediaElements.length;

	for (i = 0; i < total; i++) {
		new MediaElementPlayer(mediaElements[i], {
			pluginPath: '../build/',
		});
	}
});
```

**Comment by rafa8626** [comment]
Let me know if it works for you

**Comment by mzen1** [comment]
yes! thank you so much Raphael!!

**Comment by rafa8626** [comment]
Glad it worked for you.

----------
Please star us at https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. to support the project, if you don't mind.It would be greatly appreciated it

**Comment by mzen1** [comment]
okay, will do. thanks again!
