### ISSUE TITLE
Control bar show event

### ISSUE THREAD

**Issue by lebanggit** [mediaelement/mediaelement-plugins#40]
I having try develop a plugin with simple download button. It will embed on top-right corner of mejs player.

I will show/hide when user hover to player (like control bar).

Please add event of this.

**Comment by jimmywarting** [comment]
Why not add it to the media bar at the bottom?

**Comment by lebanggit** [comment]
All Feature icons on media bar.... Very tangled

**Comment by rafa8626** [comment]
@lebanggit This event exists already, but it must be attached to the media's `container` element:
```javascript
new MediaElementPlayer('player1', {
     // Your configuration
    success: function (media) {
        media.closest('.mejs__container').addEventListener('controlsshown', function() {
               // Your code when control bar is being displayed...
        });

        media.closest('.mejs__container').addEventListener('controlshidden', function() {
               // Your code when control bar is being hidden...
        });
    }
});
```
Let me know if it works for you

**Comment by lebanggit** [comment]
@rafa8626: How to implement this on the buildxxx function in the plugin?

How can i get media object?

**Comment by rafa8626** [comment]
```javascript
buildXXXX: function (player, controls, layer, media) {
       player.container.addEventListener('controlsshown', function() {
              // your code...
       });
}
```

**Comment by lebanggit** [comment]
Great!!! Success. But this button just working after media playing....

@rafa8626 : You should add a top bar controls container like media controls.

It contain share, download, report button..... and title of video


![](http://lebang.vn/docs/mejs.jpg)

**Comment by lebanggit** [comment]
mejs__overlay mejs__layer mejs__overlay-play

Is top layer and width 100%, height 100%.

When media stop, all control behind not woking.

**Comment by rafa8626** [comment]
You might want to include the alwaysShowControls: true configuration; see if that works for you

**Comment by lebanggit** [comment]
Not working..

Maybe set height of mejs__overlay-play

![](http://lebang.vn/docs/me2.jpg)

**Comment by rafa8626** [comment]
If you can share the URL so I can take a look I'd appreciate it

**Comment by lebanggit** [comment]
http://demo.lebang.vn/embed.html

Focus the **Download** button

**Comment by rafa8626** [comment]
Just set `mejs__top_controls` class `z-index` to 5, and that should do it

**Comment by lebanggit** [comment]
Wow..... great.... resolved

**Comment by rafa8626** [comment]
Glad to know that.

----------
Please star us at https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. to support the project, if you don't mind.It would be greatly appreciated it
