### ISSUE TITLE
ChromeCast not work in Google Chrome for android

### ISSUE THREAD

**Issue by FrancoJoaquinTorres** [mediaelement/mediaelement-plugins#42]
Hello, I'm trying ChromeCast plugin for Android devices (smartphone, tablet), but this does not show to send to ChromeCast through the Chrome browser, only work in PC

**Comment by rafa8626** [comment]
Thanks for reporting this. I'll try to find an Android device to check this. Did you have any errors on the console?

**Comment by FrancoJoaquinTorres** [comment]
I can not see the console in the chrome browser for Android. However, the ChromeCast icon is not visible when trying to watch a video.

**Comment by rafa8626** [comment]
Yeah I noticed that too. Do you mind asking on the Chromecast forum about this issue using a sender in a web app run in Android please? I'm dealing with another issue related to tracks not being played

**Comment by rafa8626** [comment]
I'm not sure why the isAvailable variable in the code is false on mobile devices that's the key to solve this issue

**Comment by FrancoJoaquinTorres** [comment]
Thanks @rafa8626 the problem resolve when var loadedCastAPI = true;

**Comment by FrancoJoaquinTorres** [comment]
@rafa8626 Where in the code is that?

**Comment by rafa8626** [comment]
Check https://github.com/mediaelement/mediaelement-plugins/blob/master/dist/chromecast/chromecast.js#L472 and let me know your thoughts, please. Thanks

**Comment by FrancoJoaquinTorres** [comment]
@rafa8626 i think from here https://github.com/mediaelement/mediaelement-plugins/blob/master/dist/chromecast/chromecast.js#L572 to here https://github.com/mediaelement/mediaelement-plugins/blob/master/dist/chromecast/chromecast.js#L575 should be out of here https://github.com/mediaelement/mediaelement-plugins/blob/master/dist/chromecast/chromecast.js#L469

**Comment by rafa8626** [comment]
The thing is that in the code samples they provide they indicate that that call should be made before  the script gets called. Have you tried doing what you stated above with success? I just don't have a device to try this

**Comment by rafa8626** [comment]
Any updates with this?

**Comment by rafa8626** [comment]
Closing this issue since no answers have been posted in more than 2 weeks. If you want this to be reopen, let us know. Thanks. Please star both https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. that have a GitHub account to do the same to support the project, if you don't mind. It would be greatly appreciated it.
