### ISSUE TITLE
Need demo about ads, context-menu

### ISSUE THREAD

**Issue by lebanggit** [mediaelement/mediaelement-plugins#43]
I have try but it not working....

@rafa8626 : Please push one demo about this?

**Comment by rafa8626** [comment]
Ok I'll work on putting an Ad on the main demo for this repo this week

**Comment by rafa8626** [comment]
@lebanggit Demo file has been updated; please check master branch and let me know. Context Menu has some issues so I didn't include it. But I will once I solve those issues. Thanks.

**Comment by rafa8626** [comment]
@lebanggit Just FYI the context menu should be working now and it's integrated on the demo file
