### ISSUE TITLE
Skip-back feature broken

### ISSUE THREAD

**Issue by joelkraft** [mediaelement/mediaelement-plugins#47]
Installing the skip-back feature in a mediaelement player, then clicking the skip-back icon fires this error:
`Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.`
The video does not skip back.

I have a pull request ready to go for this issue.

**Comment by rafa8626** [comment]
I'll be happy to review it if you submit it. Thanks

**Comment by rafa8626** [comment]
Closing issue since fix has been merged. Thanks for reporting this

**Comment by rafa8626** [comment]
Please star us at https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. to support the project, if you don't mind.It would be greatly appreciated it
