### ISSUE TITLE
HLS Support in Chrome Browsers

### ISSUE THREAD

**Issue by tnapoleon74** [mediaelement/mediaelement-plugins#53]
When trying to access a HLS stream (.m3u8) in Chrome via API get Uncaught (in promise) DOMException: Failed to load because no supported source was found when trying to set the SRC variable. 

Example:

http://download.alldigital.net/00000001/00000001/MCWE/player/mediaelement-mediaelement-d7843f9/demo/player_24.html

May want to have simple sample that includes promise set up required for newer Chrome Browsers.

**Comment by rafa8626** [comment]
I didn't get that error when checking your website; I used Chrome latest version on Mac
<img width="1375" alt="screen shot 2017-05-19 at 4 26 29 pm" src="https://cloud.githubusercontent.com/assets/910829/26265669/08a89c00-3cb0-11e7-8977-0767e24575e9.png">

**Comment by rafa8626** [comment]
Please star both https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. that have a GitHub account to do the same to support the project, if you don't mind. It would be greatly appreciated it.

**Comment by umh** [comment]
Hi, 

Im having the same issue with desktop,  VAST works good on ios and android, but on desktop it plays the ad, but does not play the trailing m3u8 stream.  Please check https://goo.gl/Wh94gf

**Comment by rafa8626** [comment]
@tnapoleon74 Any updates on this? @umh please see comments on #55

**Comment by rafa8626** [comment]
Closing this issue since no answers have been posted in more than a week; if you like this to be reopened, please let us know. Thanks
