### ISSUE TITLE
HLS VAST Uncaught (in promise) DOMException: Failed to load because no supported source was found when trying to set the SRC variable.

### ISSUE THREAD

**Issue by umh** [mediaelement/mediaelement-plugins#55]
Hi, 

Im having an issue, with desktop,  VAST works good on ios and android, but on desktop it plays the ad, but does not play the trailing m3u8 stream and throws the error Uncaught (in promise) DOMException: Failed to load because no supported source was found when trying to set the SRC variable.. If we disable vast, the m3u8 stream plays fine.  Please check https://goo.gl/Wh94gf

**Comment by rafa8626** [comment]
For starters, your manifest is throwing a 403, so just because of that it won't play at all. Check that and you should be fine
<img width="738" alt="screen shot 2017-05-23 at 8 51 40 pm" src="https://cloud.githubusercontent.com/assets/910829/26382361/bce4f0b4-3ff9-11e7-92ab-5050853098c9.png">

**Comment by umh** [comment]
hi, when we play same stream without VAST, it works fine:
https://goo.gl/VTt3Ol

when we play a different stream with vast, it behaves the same way:
https://goo.gl/1fJqob

**Comment by rafa8626** [comment]
@umh Please download the master branch and test this again; you should be good now. Let me know and please star both https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. that have a GitHub account to do the same to support the project, if you don't mind. It would be greatly appreciated it.

**Comment by rafa8626** [comment]
Closing this issue since no answers have been posted in more than a week; if you like this to be reopened, please let us know. Thanks
