### ISSUE TITLE
[chromecast] seems to registerElement multiple times

### ISSUE THREAD

**Issue by jimmywarting** [mediaelement/mediaelement-plugins#56]
I got a single page website, so when I create a new player i get this error:

> Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'google-cast-button'. A type with that name is already registered.

**Comment by rafa8626** [comment]
Can you send me a URL to check this please?

**Comment by jimmywarting** [comment]
https://jsfiddle.net/Luuwnjfm/

**Comment by rafa8626** [comment]
It can only be one sender per page; I implemented something that might help you:
https://jsfiddle.net/Luuwnjfm/5/

Let me know your thoughts

**Comment by jimmywarting** [comment]
Can use that

But I Think this will be a recurring issue among others so I think it would be best if built in to the plugin

**Comment by rafa8626** [comment]
Please download the master branch; I was able to put a restriction so only one sender per page is now allow and you can use https://jsfiddle.net/Luuwnjfm/1/ without any hacks. Let me know

**Comment by jimmywarting** [comment]
Works

**Comment by rafa8626** [comment]
I'm glad it worked for you

**Comment by jimmywarting** [comment]
Hmm, didn't work where we'll 

The Chromecast don't appear after I set a video source. And the check for the button makes it never appear cuz it's always true?

**Comment by rafa8626** [comment]
I'll check this on your scenario; do you have a fiddle that I can use for testing scenario?

**Comment by jimmywarting** [comment]
If you get [this fiddle](https://jsfiddle.net/Luuwnjfm/7/) to work without modification then i think you have solved both my Chromecast bugs

 - The video source should be possible to set after you have initiated a MediaElementPlayer and you got yourself a visible ChromeCast icon
 - The google-cast-button shouldn't throw an error when initiating a new MediaElementPlayer on the same page more then once

**Comment by rafa8626** [comment]
@jimmywarting Can you try this Fiddle and check if that solves your issue? https://jsfiddle.net/Luuwnjfm/8/

**Comment by rafa8626** [comment]
Any updates on this?

**Comment by jimmywarting** [comment]
The chromecast isn't available after I set a source

**Comment by rafa8626** [comment]
Hmmm I'll take a look at this again. It was working for me before

**Comment by jimmywarting** [comment]
maybe that isn't the problem. `document.createElement('x-y').constructor === HTMLElement` is always equal to `true` 

> (as you can see console.log(document.createElement('google-cast-button').constructor === HTMLElement) prints true, which makes the script to bail out early

which makes [this](https://github.com/mediaelement/mediaelement-plugins/blob/master/src/chromecast/chromecast.js#L441) code return early without building the cast button

**Comment by rafa8626** [comment]
Hmmmm yeah I need to research how to check if the button has been truly registered, because I thought that would be enough. I'll keep you posted

**Comment by rafa8626** [comment]
@jimmywarting OK I think I finally got it; I added a new Fiddle so you can see the end result. Dealing with Chromecast is a little complicated so I'll be thinking in a better way to do this but for now you should get everything fine: https://jsfiddle.net/Luuwnjfm/13/. Let me know

**Comment by rafa8626** [comment]
@jimmywarting I have refactor MediaElement to integrate Chromecast inside the player and not as a plugin. If you can help me testing this, please test this Fiddle so it can be part of the next release: https://jsfiddle.net/Luuwnjfm/17/

**Comment by rafa8626** [comment]
FYI i have completed more work to enable errors properly on the player UI but that should affect your testing. Keep me posted since I'm planning to release this week

**Comment by rafa8626** [comment]
@jimmywarting I have 2 new branches (one for the player and one for the plugins) named the same: `mejs-new`. Please test Chromecast using them by enabling the `chromecast` feature inside your player's configuration:
```javascript
features: ['playpause', 'current', 'progress', 'duration', 'speed',  'volume', 'chromecast']
```
 **You will need to include chromecast.min.js** after the `MediaElement` library:
These new branches had addressed many issues in terms of integrating properly Chromecast and achieved the dual-nature of Chromecast and MediaElement, and had integrated all the fixes that will go for the next release. Please let me know your findings. Thanks again for testing this.

**Comment by ManoAbraham** [comment]
@rafa8626 Thanks for your work. Testing your new code. I'm getting following tag for chromecast button `<button type="button" is="google-cast-button" aria-controls="mep_0" title="Chromecast" aria-label="Chromecast" tabindex="0" style="display: none;"></button>`
 style="display: none;" cause cast button to disappear. once it's removed rest works fine.
![image](https://user-images.githubusercontent.com/29570024/27329476-529af830-55d3-11e7-98ec-1ed945e9a4dc.png)

**Comment by rafa8626** [comment]
The `display: none` remains there to make sure the Cast is found or not. It shouldn't be hidden once Cast is detected. Is that your scenario? I merged the `mejs-new` branch into master. Can you confirm this issue exists in master?

**Comment by rafa8626** [comment]
Closing this issue since all issues related to Chromecast have been discussed and addressed on https://github.com/mediaelement/mediaelement/issues/2273
