### ISSUE TITLE
[chromecast] trying to parse mimetype from url when there is none

### ISSUE THREAD

**Issue by jimmywarting** [mediaelement/mediaelement-plugins#57]
I'm creating a player first without a source and getting this error:
> error building chromecast Error: `url` argument must be a string

The reason is cuz i have not put any src on the video yet.
I'm doing it afterwards since i need multiple sources `player.setSrc([...])`

**Comment by jimmywarting** [comment]
```js
let player = new MediaElementPlayer(video, {
  features: ['chromecast']
})
player.setSrc([...])
```

**Comment by rafa8626** [comment]
@jimmywarting I think this is fixed now; please download the master branch and let me know. Thanks

**Comment by rafa8626** [comment]
Closing this to favor #56
