### ISSUE TITLE
VPaid support

### ISSUE THREAD

**Issue by ron666** [mediaelement/mediaelement-plugins#6]
_From @info2000 on May 23, 2014 22:23_

Hi, i want know if is vpaid supported by some plugin or external library.
If no, i will sponsor it

Thanks

_Copied from original issue: johndyer/mediaelement#1205_

**Comment by ron666** [comment]
@info2000 Closing old issues. If you'd like to reopen this, let us know. Thanks!

**Comment by ron666** [comment]
_From @DrLightman on January 21, 2017 14:30_

Hello, what's the status of this feature at present? Is one able to add let say a VAST as preroll to a video?

**Comment by ron666** [comment]
Not yet is in the queue but we haven't done any work. Any PR are welcome for this or I'll keep you posted

**Comment by ron666** [comment]
Vast is currently available but you'll need to bundle a custom file. See Guidelines for more instructions

**Comment by ron666** [comment]
I'll check https://github.com/MailOnline/videojs-vast-vpaid and see what's needed

**Comment by ron666** [comment]
@gitEdMax this feature has been worked on. Please provide feedback here. Thanks

**Comment by ron666** [comment]
@gitEdMax I got solved the issue with tracking. Please download the master branch of this repo and use `ads` and `ads-vast` to test once more. Thanks for your patience.

**Comment by ron666** [comment]
@gitEdMax BTW if you can provide more robust VAST and VPAID URLs to check what's missing to integrate in the plugin I'd appreciate it.

**Comment by gitEdMax** [comment]
Thanks very much Rafael !

 

Now ready for VAST and VPAID

 

Great job!

Ed

 

Van: Rafael Miranda [mailto:notifications@github.com] 
Verzonden: donderdag 30 maart 2017 00:39
Aan: mediaelement/mediaelement-plugins <mediaelement-plugins@noreply.github.com>
CC: Ed <info@maxiweb.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mediaelement/mediaelement-plugins] VPaid support (#6)

 

@gitEdMax <https://github.com/gitEdMax>  I got solved the issue with tracking. Please download the master branch of this repo and use ads and ads-vast to test once more. Thanks for your patience.

**Comment by ron666** [comment]
Thanks for sharing your knowledge. Last thing I'll do it to rename the file to `ads-vast-vapid`
