### ISSUE TITLE
mediaelement playlist works in previous version but not this version of mediaelement

### ISSUE THREAD

**Issue by rob030** [mediaelement/mediaelement-plugins#65]
Hi
I am not sure whether I should post this here or on the main mediaelement download site. I see there is a plugin for a playlist here but not sure how to implement it.
On the previous version of mediaelement I had the following code, which I think I obtained from mediaelement resources.
HTML
```
<head>      
<script src="js/jquery.1.12.4.min.js" ></script>  
    <script src="build/mediaelement-and-player.js"></script>`
<link rel="stylesheet" href="build/mediaelementplayer.css" />
<script type="text/javascript">		
			// global for movie player
			var player;
			$(document).ready(function () {
				player = new MediaElementPlayer('#videoPlayer');
			});
			function ChangeVideo(vid) {
				var newSrc = '';
				switch (vid) {
					case 1:
						newSrc = 'video/big_buck_bunny_480p_surround-fix.mp4';
						break;
					case 2:
						newSrc = 'video/sintel-1024-surround.mp4';
						break;
					case 3:
						newSrc = 'https://www.youtube.com/watch?v=twYp6W6vt2U';
						break;	
				}				
				player.setSrc(newSrc);			 
				player.load();
				player.play();
				return false;
			}		 
		</script>
</head>
<body>
<video id="videoPlayer" style="width:100%; height:100%;" src="video/big_buck_bunny_480p_surround-fix.mp4" width="100%" height="100%" poster="video/bbb.png"></video>
		<a href="#" onclick="return ChangeVideo(1)">video 1</a><br />
		<a href="#" onclick="return ChangeVideo(2)">video 2</a><br />
		<a href="#" onclick="return ChangeVideo(3)">video 3</a>
</body>
```
I have looked at the documents, tried with demo.js(this works but I have no idea on how to use a list rather than the select dropdown -eventually I want to use images in a carousel). I have been at it for days. Any help in this matter would be greatly appreciated.
Thanks in advance
Rob

**Comment by rafa8626** [comment]
@rob030 If you are using the latest version you should use:
```javascript
player = new MediaElementPlayer('videoPlayer');
```
because your code has a typo. 
This is the code I tried and worked for me (FYI, you don't need jQuery for the player anymore):
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../build/mediaelementplayer.css" />
    <script src="../build/mediaelement-and-player.js"></script>`
    <script type="text/javascript">
	    // global for movie player
	    var player;
	    document.addEventListener('DOMContentLoaded', function() {
		    player = new MediaElementPlayer('videoPlayer');
	    });
	    function ChangeVideo(vid) {
		    var newSrc = '';
		    switch (vid) {
			    case 1:
				    newSrc = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';
				    break;
			    case 2:
				    newSrc = 'https://media.w3.org/2010/05/sintel/trailer.mp4';
				    break;
			    case 3:
				    newSrc = 'https://www.youtube.com/watch?v=twYp6W6vt2U';
				    break;
		    }
		    player.setSrc(newSrc);
		    player.load();
		    player.play();
		    return false;
	    }
    </script>
</head>
<body>
<div style="width: 800px;height:600px">
<video id="videoPlayer" style="width:100%; height:100%;" src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" width="100%" height="100%"></video>
</div>
<a href="#" onclick="return ChangeVideo(1)">video 1</a><br />
<a href="#" onclick="return ChangeVideo(2)">video 2</a><br />
<a href="#" onclick="return ChangeVideo(3)">video 3</a>
</body>
</html>
```
Let me know if it works for you and please star both https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. that have a GitHub account to do the same to support the project, if you don't mind. It would be greatly appreciated it.

**Comment by rob030** [comment]
Hi Rafael,
That works very well. Days and days I have spent trying to sort this and the demo. You are a star. Thankyou very very much.
I really appreciate it.
Will definitely be starring both. When I have finished my project and all works well, mediaelement will be getting alot of publicity. I always use mediaelement for any websites that I built that require video.
Again, thanks Rafael
Cheers
Rob

**Comment by rafa8626** [comment]
Great. We really want more people to star the project. We don't ask for anything but that. If you can help us with that, that would be awesome. It is good to know that this worked for you. :)
