### ISSUE TITLE
Cannot set property 'mejs.ad-skip' of undefined

### ISSUE THREAD

**Issue by Santana1053** [mediaelement/mediaelement-plugins#66]
```
ads.min.js:12 Uncaught TypeError: Cannot set property 'mejs.ad-skip' of undefined
    at Object.s.1 (ads.min.js:12)
    at t (ads.min.js:12)
    at e (ads.min.js:12)
    at ads.min.js:12
```

**Comment by Santana1053** [comment]
WordPress uses version https://github.com/mediaelement/mediaelement/tree/2.20.0 and this is not compatible

**Comment by rafa8626** [comment]
Can you share a URL to check this issue please? This means that the i18n is not there and that's weird since MediaElement has it by default. If you are not using the player or the reference to the player is after the reference to the plugin that could be the cause of this

**Comment by rafa8626** [comment]
Please consider star both https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins on each repository by clicking on the Star button on the top right of the page, to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. that have a GitHub account to do the same to support the project, if you don't mind. It would be greatly appreciated it.

**Comment by Santana1053** [comment]
Sure, I've been working off localhost. Give me a little bit to setup a public facing development site that I can demo this issue for you.
