### ISSUE TITLE
Live HLS over Chromecast

### ISSUE THREAD

**Issue by thisanimus** [mediaelement/mediaelement-plugins#67]
I receive the following error when streaming a live HLS via the Chromecast plugin.
``chromecast.js:294 Uncaught (in promise) TypeError: mediaElement.originalNode.getCurrentTime is not a function
    at chromecast.js:294
    at <anonymous>
``

Prerecorded .m3u8 files stream via the chromecast plugin just fine.  It's only the live .m3u8 videos that are throwing this error.  I understand that a live HLS feed may not have a timecode associated with it, does this prevent mediaelement.js+chromecast.js from working?  Is there even a way to fix this?

**Comment by rafa8626** [comment]
Can you provide a URL so I can see this issue? I'm currently working on fixing something related to it and might be good to integrate that fix as well

**Comment by thisanimus** [comment]
I'll set up a test site tomorrow and post a link.

**Comment by rafa8626** [comment]
Any updates on this? I finished a major refactor and I wanna test it with your issue to make sure we are all covered.

**Comment by thisanimus** [comment]
Sorry for the delay.  Here is a test site using the latest release of mejs and mejs-plugins.

http://thisanimus.com/streamtest/demo/

**Comment by rafa8626** [comment]
I tried to reproduce it, but it returned a 403. I'm gonna ask you to test the development branch on the MediaElement project and let me know if everything works as you expected on that branch. You won't need the plugin anymore since Chromecast is integrated in the player core on that branch; you will just need to enable it via features using the keyword `chromecast`. Let me know your findings, please, so this can go to the next release

**Comment by thisanimus** [comment]
- Found another live stream that seems to be working now.
- Using the dev branch
- Get the following error when initiating the cast:

```
[ 12.006s] [cast.framework.EventTarget] Handler for isConnectedChanged event failed: TypeError: this.media.originalNode.getSrc is not a function
M @ cast_framework.js:14
```

**Comment by rafa8626** [comment]
Thanks for testing this. I pushed earlier some changes/fixed to the dev branch if you can test this again I'll appreciate it.

**Comment by rafa8626** [comment]
Just as an FYI I may end up putting this as a plugin again but with the new approach I took. I'm just waiting for more tests and I'll proceed to do that because the file size increased quite a bit and I'd like to keep it as light as possible

**Comment by thisanimus** [comment]
Thanks for your thoughtful approach.  It's because of this kind of discipline that MEJS is such a fantastic plugin. The quality of work you devs put into this project is mind-blowing.  Keep it up.

**Comment by rafa8626** [comment]
@thisanimus OK I have 2 new branches (one for the player and one for the plugins) named the same: `mejs-new`. Please test them using the following configuration for your scenario **INCLUDING chromecast.min.js**:
```javascript
new MediaElementPlayer('player1', {
	// This is needed to make Jump Forward to work correctly
	autoRewind: false,
        castIsLive: true,
	features: ['playpause', 'current', 'progress', 'duration', 'speed',  'volume', 'chromecast']
});
```
These new branches had addressed many issues in terms of integrating properly Chromecast and achieved the dual-nature of Chromecast and MediaElement. Let me know your findings and thanks again for testing this

**Comment by thisanimus** [comment]
Using mejs-new and mejs-new-plugins the .m3u8 won't play in-browser, it throws the following error:

```
mediaelement-and-player.min.js:12 hlsError 
Object {type: "mediaError", parent: "main", details: "bufferAppendError", fatal: false}
u	@	mediaelement-and-player.min.js:12
i.emit	@	hls.min.js:1
s.trigger	@	hls.min.js:5
value	@	hls.min.js:2
value	@	hls.min.js:2
value	@	hls.min.js:5
value	@	hls.min.js:5
i.emit	@	hls.min.js:1
s.trigger	@	hls.min.js:5
value	@	hls.min.js:3
value	@	hls.min.js:5
value	@	hls.min.js:5
i.emit	@	hls.min.js:1
s.trigger	@	hls.min.js:5
value	@	hls.min.js:4
```

**Comment by rafa8626** [comment]
Interesting I tested the same page you sent me last night with both branches. Let me take a pick again and I'll let you know

**Comment by thisanimus** [comment]
This .m3u8 works:http://109.68.190.192:1935/WEB_Smilik/Smilik.stream/playlist.m3u8

This one throws the above error: https://content.uplynk.com/channel/bd25cb880ed84b4db3061b9ad16b5a3c.m3u8

**Comment by rafa8626** [comment]
Oh gotcha. Let me check this other one. The one above worked for me as well

**Comment by thisanimus** [comment]
Malformed stream maybe?  It's from Verizon, so I would have expected that it would be standards-compliant.

**Comment by rafa8626** [comment]
It's very likely. But here's the thing: I checked this on the HLS.js website and this is the only thing I see:
<img width="893" alt="screen shot 2017-06-16 at 10 40 56 am" src="https://user-images.githubusercontent.com/910829/27231352-5d323642-5280-11e7-8f59-086621c3f914.png">
Maybe it's something with the HLS settings that need to be changed. Let me check that

**Comment by rafa8626** [comment]
In your player configuration, add this:
```javascript
hls: {
	autoStartLoad: true
}
```
I think that will solve your issue

**Comment by rafa8626** [comment]
```javascript
new MediaElementPlayer('player1', {
	// This is needed to make Jump Forward to work correctly
	autoRewind: false,
        castIsLive: true,
        hls: {
	    autoStartLoad: true
        },
	features: ['playpause', 'current', 'progress', 'duration', 'speed',  'volume', 'chromecast']
});
```

**Comment by thisanimus** [comment]
No dice on the hls config, however setting preload="metadata" on the video tag makes it work.  And the chrome cast works as well.

**Comment by rafa8626** [comment]
Interesting. I'll explore some more about this scenario. I really appreciate your testing. Is there anything else that needs to be added to this ticket, or can be closed?

**Comment by thisanimus** [comment]
Looks good to me.  When do you think megs-new will be merged into the main branch?

**Comment by rafa8626** [comment]
I just need to fix part of the behavior when using React, because there is a big issue using the plugin in combination with React, but I'll take a look at that today. Potentially, next week I'll release these changes on both branches

**Comment by thisanimus** [comment]
Great, I'll keep my eyes open for it.  Thanks again for all your hard work!

**Comment by rafa8626** [comment]
You are welcome. I just want this player to be the best one; and with people like you testing, we only make it greater. I still don't know how to make it more popular (compared to VideoJS), but maybe its more about the website than the functionality of both

**Comment by rafa8626** [comment]
Just FYI, either you used `preload="meta"` or `preload="auto"` or use `autoplay` attribute, it will work in your scenario

**Comment by rafa8626** [comment]
Just FYI, the new code is now on master branch. It will be officially released once I address one thing with ReactJS

**Comment by tiagommferreira** [comment]
@rafa8626 Comming back on this thread, I have an error, that when I'm playing certain HLS videos/live-feeds, I get the following error: `Unknown error: session_error`

Here's an HLS URL that works: http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
And one that does not: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

I tried with the configs in this thread, but same problem :/
