### ISSUE TITLE
Vast Ad video autoplays on load

### ISSUE THREAD

**Issue by Santana1053** [mediaelement/mediaelement-plugins#71]
The regular video is not set to autoplay. When the VAST xml is parsed and the ad is injected into the video it starts to autoplay.

Additionally, the regular video is available to start playing before the vast xml is returned and the ad injected. The canplay event is happening before my ad loads.

**Comment by rafa8626** [comment]
Thanks for reporting this. I'm planning to rework this plugin and I'll add this fixes as well soon. I'll keep you posted

**Comment by gjonsson** [comment]
Yes, i noticed this also. after VAST is done the POSTROLL opens.

**Comment by rafa8626** [comment]
I checked the autoplay and that's expected functionality after the Ad finishes. The `canplay` is something I'll work during the refactor to ensure those events are linked to the original element only
