### ISSUE TITLE
Ads plugin error

### ISSUE THREAD

**Issue by Santana1053** [mediaelement/mediaelement-plugins#73]
I'm not quite sure why this is happening, but the ad video is being shown below the youtube iframe, I believe that one of them is suppose to be hidden.

Also after the ad video is done playing, it throws a javascript error and fails to play the youtube video
```
Uncaught TypeError: Cannot read property 'src' of null
    at HTMLUnknownElement.setSrc (mediaelement-and-player.js?ver=4.2.2:826)
    at DefaultPlayer.setSrc (mediaelement-and-player.js?ver=4.2.2:5241)
    at MediaElementPlayer.setSrc (mediaelement-and-player.js?ver=4.2.2:4957)
    at MediaElementPlayer.adRestoreMainMedia (ads.js?ver=2.3.0:223)
    at ads.js?ver=2.3.0:213
```
http://ottumwaradio.maudience.com/watch-man-pinned-pickup-hitting-tractor/

**Comment by Santana1053** [comment]
![image](https://user-images.githubusercontent.com/10775656/27848845-ce889fde-610d-11e7-88a4-136c1d5d6e93.png)

**Comment by rafa8626** [comment]
I'll explore this soon. Also, the rewriting of this plugin will solve this situation: YouTube plays on an iframe, and the Ad plays in a video tag, and they end up conflicting. That's why you are experiencing those issues

**Comment by Santana1053** [comment]
My client really needs to get this functionality live, is there any temporary fix that I can do to get this to work?

**Comment by rafa8626** [comment]
I'll check what we can do temporarily and keep you posted

**Comment by rafa8626** [comment]
@Santana1053 Please download the master branch and test this again. Also, I noticed that in the `features` configuration you just included `vast`;  make sure you use `ads` and `vast` to avoid any other issues. Let me know if it worked for you. Thanks.

**Comment by Santana1053** [comment]
Perfect, thank you.

Unrelated, would it be possible to show the youtube video thumbnail instead of the ad thumbnail?

**Comment by rafa8626** [comment]
If you are talking about the poster, you might need to set the specific one you desire via `poster` attribute on the video tag or in the configuration of the player. Other than that, it is not possible

**Comment by Santana1053** [comment]
Thank you for your quick responses and making this issue top priority

**Comment by rafa8626** [comment]
You are welcome I'm glad I could help you

**Comment by Santana1053** [comment]
It seems that this is still an issue :( my client sent me this screenshot on her iPhone 6S plus
![image](https://user-images.githubusercontent.com/10775656/29640745-e9689194-8825-11e7-803c-3e45266eaa6e.png)

**Comment by rafa8626** [comment]
Are you using the latest version of the player?

**Comment by Santana1053** [comment]
I updated the player and the ad plugin. This issue has gone away now, but my other issue #86 is still ongoing
