### ISSUE TITLE
Split controlbar settings and list of plugins

### ISSUE THREAD

**Issue by KhodyrevDS** [mediaelement/mediaelement-plugins#74]
If I want to add some plugin I cant set
`features: ['myplugin']`
because I will have no any controls and I must specify all default controls and my plugin
`features: ['playpause', 'current', 'progress', 'duration', 'tracks', 'volume', 'fullscreen', 'myplugin']`

It will be fine to split contolbar settings and list of used plugins.

**Comment by rafa8626** [comment]
Thanks for the suggestion I'll check how can this be integrated and keep you posted

**Comment by rafa8626** [comment]
Sorry for the delay. Please download the master branch of the player. Now a `useDefaultControls` is set to false. If you set it to true, it will allow you to get the default control bar elements in strict order and then you can just append more plugins using `features`. Let me know if it worked for you and thanks for reporting this. Please star the project so we continue supporting it

**Comment by rafa8626** [comment]
Closing this issue since feature is now in place. Thanks for reporting this and please star this project to continue supporting it
