### ISSUE TITLE
Speed selector options hidden behind audio player

### ISSUE THREAD

**Issue by billyeh** [mediaelement/mediaelement-plugins#75]
![untitled](https://user-images.githubusercontent.com/2067277/28392293-2a1f3824-6c96-11e7-8fd3-339bd84d7d10.png)

You can see where my mouse is that the speed plugin selector isn't tall enough to display all the options. 

Setting the `.mejs__speed-selector, .mejs-speed-selector` height to 150px instead of 100px fixes it.

**Comment by rafa8626** [comment]
Thanks I'll fix this as soon as I can. Please star the project to continue supporting it

**Comment by rafa8626** [comment]
Done. It has been fixed. Thanks again for reporting this and please star us to gave this repo more popularity
