### ISSUE TITLE
quality plugin , group ?

### ISSUE THREAD

**Issue by lee149205** [mediaelement/mediaelement-plugins#82]
I have 
```
<source type="video/mp4" src="<?= $mp4 ?>" data-quality="SD" />
            <source type="video/mp4" src="<?= $hd ?>" data-quality="HD" />
            <source type="video/webm" src="<?= $webm ?>" data-quality="SD"/>
```

But, it display 3 options ( “SD” , “HD”, “SD”)
How to group ? (only show 2 options "SD" , "HD")

**Comment by rafa8626** [comment]
The plugin is not ready to deal with grouping currently; the best for now is to come up with different names for your sources

**Comment by rafa8626** [comment]
If you are interested on creating a PR, I'd be happy to review it. Please star our projects to continue supporting them. Thanks
