### ISSUE TITLE
Hint to add plugins to the "features" option

### ISSUE THREAD

**Issue by cezzre** [mediaelement/mediaelement-plugins#84]
I was trying to install MediaElement.js with [Source Chooser](https://github.com/mediaelement/mediaelement-plugins/blob/master/docs/source-chooser.md) and I struggled a bit before understanding that I had to add `sourcechooser` to the list of features.

Would be great to add a hint somewhere in the docs.

```javascript
new MediaElementPlayer('#player', {
	features: ['playpause', 'current', 'progress', 'duration', 'volume', 'sourcechooser'],
});
```

**Comment by rafa8626** [comment]
If you wanna create a PR for this, I'd be happy to review it. You might wanna add those on each of the docs as a Javascript mini snippet

**Comment by rafa8626** [comment]
A snippet for each plugin has been added on the docs area. Closing this issue and please star the project to support it. Thanks
