### ISSUE TITLE
HLS source switcher

### ISSUE THREAD

**Issue by saeedrm6** [mediaelement/mediaelement-plugins#87]
Hello
I use hls m3u8 to play video file, But I cant switch the quality 
Please Help me...
My test Folder : http://click.ir/mediaelement/index.html
with thanks ♥

**Comment by rafa8626** [comment]
The Quality plugin acts similar to https://github.com/mediaelement/mediaelement-plugins/blob/master/docs/source-chooser.md; if you have only one HLS source nothing is going to happen. The quality for HLS depends on the Manifest file itself, not on the plugin

**Comment by saeedrm6** [comment]
I have 3 HLS file, I enter my sources like this : 
<source src="http://localhost/newclick/wp-content/uploads/2017/08/Tile-HD.m3u8" type="application/x-mpegURL">
                  <source src="http://localhost/newclick/wp-content/uploads/2017/08/Tile-SD.m3u8" type="application/x-mpegURL">
                  <source src="http://localhost/newclick/wp-content/uploads/2017/08/Tile-mobile.m3u8" type="application/x-mpegURL">

and also I include the switcher dependies to project , but when I switch the source, I give this error in console of chrome: 
Uncaught (in promise) DOMException: The element has no supported sources.

I update my codes in this directory : 
http://click.ir/mediaelement/

please help me...

**Comment by rafa8626** [comment]
I see an error in your site, because you have most of the code I use for the demo file, but the markup you are using is different. Change your entire `demo.js` for this:
```javascript
document.addEventListener('DOMContentLoaded', function () {
	var mediaElements = document.querySelectorAll('video, audio'), i, total = mediaElements.length;

	for (i = 0; i < total; i++) {
		var features = ['playpause', 'current', 'progress', 'duration', 'volume', 'contextmenu', 'ads','fullscreen', 'sourcechooser'];
		new MediaElementPlayer(mediaElements[i], {
			stretching: stretching,
			pluginPath: 'build/',
			adsPrerollMediaUrl:
 ['http://media.productionhub.com.s3.amazonaws.com/preroll.mp4'],
                        adsPrerollAdUrl: ['http://www.github.com'],
                        adsPrerollAdEnableSkip: true,
                        adsPrerollAdSkipSeconds: 1,
                       features: features
		});
	}
});
```
Once you change that, let's see if that helps. BTW, you could use the quality plugin. I pointed out the source chooser because they follow the same principle: without more sources inside the video tag, it won't work. Let me know if the snippet help. Thanks

**Comment by saeedrm6** [comment]
I changed the demo.js to new, but it doesnt works. I got this error on my console : Uncaught (in promise) DOMException: The element has no supported sources.

**Comment by rafa8626** [comment]
I tried the following code (given that I couldn't use your HLS files in my local environment) and it worked but you need to change the following line on the quality.js code:
```javascript
for (var _i6 = 0, _total7 = qualities.length; _i6 < _total7; _i6++) {
					var _src = qualities[_i6],
					    _quality = _src instanceof HTMLElement ? _src.getAttribute('data-quality') : _src['data-quality'];

					if (_quality === newQuality) {
						player.qualitiesButton.querySelector('button').innerHTML = _src.title || getQualityNameFromValue(newQuality);
						media.pause();
						media.setSrc(_src.src);
						media.load();
						//media.addEventListener('canplay', canPlayAfterSourceSwitchHandler);
						if (!paused) {
							media.setCurrentTime(currentTime);
							media.play();
						}
					}
				}
```
this is the code I used and worked for me:
```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MediaElement.js 3.0 - audio/video unification library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../build/mediaelementplayer.css">
    <link rel="stylesheet" href="../media/ads.css">
    <link rel="stylesheet" href="../media/quality.css">
    <style>
        html, body {
            overflow-x: hidden;
        }
        #container {
            padding: 0 20px 50px;
        }
        .error {
            color: red;
        }
        a {
            word-wrap: break-word;
        }
        code {
            font-size: 0.8em;
        }

        #ads{
            width: 468px;
            height: 60px;
            position: absolute;
            display: block;
            margin: 0 auto;
            left: 20%;
            right: 20%;
            bottom: 5%;
            z-index: 99999999999999999;
            text-align: center;
        }
    </style>
</head>
<body>
<div id="container">
    <div class="players" id="player1-container">
        <h3>Video Player</h3>
        <div class="media-wrapper">
            <video id="player1" width="640" height="360" style="max-width:100%;" poster="http://www.mediaelementjs.com/images/big_buck_bunny.jpg" preload="none" controls playsinline webkit-playsinline controls="">
                <source src="http://www.streambox.fr/playlists/test_001/stream.m3u8" type="application/x-mpegURL" data-quality="720">
                <source src="http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8" type="application/x-mpegURL" data-quality="480">
            </video>
        </div>
    </div>
</div>
<script src="../build/mediaelement-and-player.js"></script>
<script src="../media/ads.js"></script>
<script src="../media/quality.js"></script>
<script>
	document.addEventListener('DOMContentLoaded', function () {
		var mediaElements = document.querySelectorAll('video, audio'), i, total = mediaElements.length;

		for (i = 0; i < total; i++) {
			var features = ['playpause', 'current', 'progress', 'duration', 'volume', 'contextmenu', 'ads','fullscreen', 'quality'];
			new MediaElementPlayer(mediaElements[i], {
				pluginPath: 'build/',
				adsPrerollMediaUrl: ['../media/preroll.mp4'],
				adsPrerollAdUrl: ['http://www.github.com'],
				adsPrerollAdEnableSkip: true,
				adsPrerollAdSkipSeconds: 1,
				features: features
			});
		}
	});
</script>

</body>
</html>
```

**Comment by rafa8626** [comment]
By the way, I'm not maintaining the project anymore. I'm just currently checking PRs and wrapping things for WordPress so the latest version of MediaElement is integrated in the 4.9 release

**Comment by saeedrm6** [comment]
thanks for your help. the problem solved in Firefox and Microsoft Edge but I have same error on Google Chrome (The element has no supported sources.) when I change the quality. If possible please help me for solve that. 
thanks a lot

**Comment by saeedrm6** [comment]
the error is from args in the line of 868 : 
setTimeout(function () {
				t.mediaElement.renderer[methodName](args);
			},

**Comment by rafa8626** [comment]
Yeah it's weird because with the markup I posted above, I had no issues with Chrome. Also I was using the master branch of the player

**Comment by saeedrm6** [comment]
I am exactly using above your [link...](https://github.com/mediaelement/mediaelement-plugins/issues/87#issuecomment-325328367)
I dont have any error or issue in mobile(chrome, firefox, ...) but I still have this error in desktop version of chrome (Version 60.0.3112.113 (Official Build) (64-bit)).

**Comment by rafa8626** [comment]
Well again, I used the master branch on the project and in your case you are using version 4.2.3. That's the only difference I see

**Comment by saeedrm6** [comment]
ohhh... yeah I use the latest version of mediaelementjs and my issue has solved...
thanks a lottttttttttt
wish the best for you dear Rafael ♥♥♥
