### ISSUE TITLE
Autoplay of all sources in playlist

### ISSUE THREAD

**Issue by LeaFoissac** [mediaelement/mediaelement-plugins#90]
When the playlist plugin is used and
when the audio/video has finished to read
Then I want that the following source to be automatically read

**Comment by rafa8626** [comment]
It should be doing this already. Check the demo file for more reference. I just tested both video and audio using the current demo file and they both worked. RTMP has an issue currently but video is completely fine

**Comment by rafa8626** [comment]
Please star the project to support it
