### ISSUE TITLE
[Q] Select Quality From Single .mpd?

### ISSUE THREAD

**Issue by Gungrave223** [mediaelement/mediaelement-plugins#92]
Question....is it possible to set up the quality.js plugin to auto generate the quality from the .mpd playlist file? 

I'm trying to avoid having to set 20 thousand source for a single video...and want to just uses the different quality videos already created for the mpeg dash stream.

**Comment by rafa8626** [comment]
No, this plugin just considers the `source` tags, not the internals of a manifest file. If you wanna provide a PR to enhance this, I'd be happy to review it

**Comment by goldensky09** [comment]
May i know if my m3u8 file has 4 video quality, how to get the quality menu. a small code snippet to explain will help.

**Comment by Gungrave223** [comment]
> May i know if my m3u8 file has 4 video quality, how to get the quality menu. a small code snippet to explain will help.

It depends on how you created your playlist...I personally use aws media element to convert my mp4 into hls video...

During the conversion process, I have aws create different playback quality for the different bandwidth support...then I have a master playlist that's used to auto switch between the playback quality base on the end user bandwidth...

So to answer your question...there is no code to know if you're .m3u8 file have 4 video quality...it all depends on how you converter your original video into hls format.

**Comment by berryamin** [comment]
Closing, as the feature has been pushed to master

**Comment by MrAbdelaziz** [comment]
Hi guys thanks for the support 👍 , I don't understand how to implement that with MPD source for example :
 <source type="application/dash+xml" src="http://localhost/stream/v2/stream/vid/vid.mpd" />
vid.mpd with multi QL
