### ISSUE TITLE
play m3u8 audio file

### ISSUE THREAD

**Issue by saeedrm6** [mediaelement/mediaelement-plugins#95]
Hello
I want to play .m3u8 audio file with mediaelementjs but I give error ;
``
<audio     class="mep-playlist"
                   data-showplaylist="false"
                   width="400"
                   controls="controls"
                   preload="auto">
            <source src="http://localhost/navaei/wp-content/uploads/2017/10/shahab-tark-1-stream.m3u8" type="application/x-mpegURL"/>
</audio>
``

script in the footer of html :

> <script>
$('.mep-playlist').mediaelementplayer({
            features: ['playlistfeature', 'prevtrack', 'playpause', 'nexttrack',  'current', 'progress', 'duration', 'volume', 'qual'],
            audioVolume: "vertical", // just like video player
            shuffle: false,
            loop: false,
			pauseOtherPlayers: true,
            success: function(mediaElement, domObject) {
				if (isMobileDevice() == false) {
					if ($(".mejs-playpause-button").hasClass('mejs-play')) {
						$(".mejs-playpause-button").removeClass('mejs-play');
						$(".mejs-playpause-button").addClass('mejs-pause');
					}
				}
				mediaElement.play();
                mediaElement.addEventListener('canplay', function() {
                    // Player is ready
					// if (isMobileDevice == true) {
						// $('[aria-label="Play"]').click();
					// }
                }, false);
            },
            error: function() {
                //alert('Error setting media!');
                alert('error!');
            }
        });

> </script>

**Comment by saeedrm6** [comment]
no idea?

**Comment by rafa8626** [comment]
I don't know if it's because you are using `localhost` in the source; have you tried using a different host?

**Comment by rafa8626** [comment]
Or it's strictly your stream.

**Comment by rafa8626** [comment]
Closing issue since no answer has been posted in a week. If you would like this to be reopene please let us know

**Comment by saeedrm6** [comment]
Hello, Excuse Me I havent access on the project... I try other sources Except 'localhost'... but I give error again

**Comment by saeedrm6** [comment]
I also copy your demo to  https://nava.ir/media/demo/
but hls in audio play dont work

**Comment by rafa8626** [comment]
You may need to post a URL where the issue can be explored. I’m not maintaining the project anymore but I can take a quick look

**Comment by saeedrm6** [comment]
I solved this issue with update to the latest version of your script...
thank you...
