### ISSUE TITLE
Change quality without playing - starts playing from the beginning

### ISSUE THREAD

**Issue by PersonalityFox** [mediaelement/mediaelement-plugins#99]
Perhaps I wanted to save traffic. I click "pause" and choose a low quality, why do I need to rewind and search my last position? This not normal. 
Am I mistaken?

**Comment by rafa8626** [comment]
@Gungrave223 your PR solved this issue?

**Comment by rafa8626** [comment]
@PersonalityFox This has been fixed in the master branch. Thanks for reporting this, and please star the project to support it. This will be released next Friday
